deployUrl=file:///Users/cer/.m2/testdeploy

eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

eventuatePluginsGradleVersion=0.14.0.BUILD-SNAPSHOT
springBootVersion=4.1.1
testContainersVersion=2.0.5

micrometerTracingVersion=1.7.1
jackson2Version=2.22.2
zipkinReporterVersion=3.5.3
aspectjVersion=1.9.25.1
reactorVersion=3.8.7
slf4jVersion=2.0.18
commonsLang3Version=3.20.0
nettyVersion=4.2.17.Final

eventuateUtilVersion=0.19.0.BUILD-SNAPSHOT

eventuateTramVersion=0.37.0.BUILD-SNAPSHOT

eventuateCommonImageVersion=0.21.0.BUILD-SNAPSHOT
eventuateMessagingKafkaImageVersion=0.21.0.BUILD-SNAPSHOT
eventuateCdcImageVersion=0.19.0.BUILD-SNAPSHOT
junitPlatformLauncherVersion=6.0.3
eventuateCdcKafkaEnableBatchProcessing=false


version=0.7.0-SNAPSHOT
