dependencies {
    api project(":eventuate-tram-spring-cloud-sleuth-tram-producer")
    api project(":eventuate-tram-spring-cloud-sleuth-tram-consumer")
    api project(":eventuate-tram-spring-cloud-sleuth-tram-reactive-producer")
    api project(":eventuate-tram-spring-cloud-sleuth-tram-reactive-consumer")
}
